services:
  - type: web
    name: dashboard-olist
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.dashboard_completo:server
    plan: free
    autoDeploy: false
